### ISSUE TITLE
No option to change line ending of a single line

### ISSUE THREAD

**Issue by rsn8887** [atom/line-ending-selector#55]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot change line ending of a single line

### Steps to Reproduce

1. load a file with mixed line endings
2. select a portion of the file
3. click on the "mixed" button to change from LF to CRLF
4. line endings in the whole file are changed

**Expected behavior:** [What you expect to happen]

Line endings should only change in the selected text. How else am I supposed to change the ending of a single line (sic)

**Actual behavior:** [What actually happens]

Line endings can only be changed in the whole file or nowhere

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
Text mode files are _required_ to use a single delimiter to show where lines end, that's why it's called the "line ending".

Atom is smart enough to be able to read files that have multiple different line endings within them, and will only touch them on lines you edit, but changing the line ending using the selector changes it for all lines in the file. That is _exactly_ what you are asking it to do after all 😉.

If you need to insert multiple different line endings in a document you'll need to open it in something that edits the file as binary data since you are explicitly _not_ treating it as a text mode document.
